services:
  base:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports: 
      - "2300:2300"
    volumes:
      - ../:/app:cached

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    ports:
      - "8080:8080"
    environment:
      API_URL: http://localhost:2300/apidocs
      